apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: app-no-ops
  labels:
    app: app-no-ops
spec:
    type: NodePort
    selector:
        app: app-no-ops
    ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
       nodePort: 38080